[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hexar_distributor = "88F6sG17xGQS1DqhXvNeppAdmnJtNFpjf9wF7hf7giew"

[programs.mainnet]
hexar_distributor = "88F6sG17xGQS1DqhXvNeppAdmnJtNFpjf9wF7hf7giew"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
